# Generated by Django 3.0.8 on 2020-11-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitojunction', '0007_userlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
