# Generated by Django 3.0.8 on 2020-11-08 02:38

from django.db import migrations
from django.db.models import F

from aitojunction.models import Place


def forwards_func(apps, schema_editor):
    prefix = 'https://s3.ap-northeast-2.amazonaws.com/static.seoulsounds.net/EPW/'
    Place.objects.filter(image_url__endswith=".jpg").update(image_url=prefix + F('image_url'))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aitojunction', '0009_auto_20201108_0232'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
